version: "3"

services:
  mysql:
    image: mariadb
    container_name: plantb-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./data/init_db.sql:/docker-entrypoint-initdb.d/a.sql"
